services:
  - type: web
    name: nikko-travel-planner
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ./database.sqlite
      - key: OPENWEATHER_API_KEY
        sync: false  # Set this in Render dashboard
    autoDeploy: true